### ISSUE TITLE
Some times can't send message

### ISSUE THREAD

**Issue by iheron** [nknorg/nkn-java-sdk#5] opened 2019-11-14 11:55 UTC
some times can't send message, but can receiving message. Use same NKNClient. 
```
private NKNClient nknClient;
nknClient = new NKNClient(identity);
......
nknClient.onNewMessage(receivedMessage -> {
}).start();
......
nknClient.sendTextMessageAsync(to, message);
```

**Comment by RealJohnSmith** [comment] 2019-11-14 18:19
Can you provide more information?
What are you trying to do, what do you expect, what do you observe and how do you do that.

Are you sending a message to yourself or somewhere else?
Because of the nature of the network, some messages don't get delivered sometimes (think of UDP protocol). Is it possible that you are observing this behaviour?

What does it mean `cant` send a message? Does the program crash? Is it just ignored?

Please include a log file. Logs are very important when trying to figure out what the problem is.

**Comment by iheron** [comment] 2019-11-15 04:20
I think websocket takes too many time to  reconnect. 
If I disconnect WIFI, Wait a minute to receive the message, but can not send message.
Wait a few minutes can be send message.
Do you konw how to  check the websocket connect  status and reconnect it.

LOG
```
I/System.out: WS#{} sending bin, {} bytes5211
    send frame: {}Framedata{ optcode:BINARY, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:211], payload:��<�Xy�3�Ic�m�(L__2__.heron.25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929(���2 �Fb�"��a�u27�3o��Ջ�[���L��'`�(:@G6Í��O��lR��@gQ�����裢u�g��Ѱ���T��"�[���O�o�,t�W5��}
I/ReactNativeJS: [AssertionError: Assertion failed]
I/ReactNativeJS: [AssertionError: Assertion failed]
I/System.out: Sending text message: {"contentType":"text","content":"11","topic":null,"timestamp":"Fri, 15 Nov 2019 04:14:13 GMT","isPrivate":true,"value":1e-7,"isMe":true,"addr":"heron.25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","username":"heron","pubKey":"25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","refersToMe":false}
I/System.out: encryptedMessage.toByteString():<ByteString@a189ff2 size=403>
E/System:  ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
I/System.out: Queueing new MessageJob
    Queueing new MessageJob end
I/System.out: Sending text message: {"contentType":"text","content":"11","topic":null,"timestamp":"Fri, 15 Nov 2019 04:14:13 GMT","isPrivate":true,"value":1e-7,"isMe":true,"addr":"heron.25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","username":"heron","pubKey":"25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","refersToMe":false}
I/System.out: encryptedMessage.toByteString():<ByteString@4640643 size=403>
E/System:  ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
E/System:  ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
I/System.out: Queueing new MessageJob
    Queueing new MessageJob end
I/System.out: Sending text message: {"contentType":"text","content":"11","topic":null,"timestamp":"Fri, 15 Nov 2019 04:14:13 GMT","isPrivate":true,"value":1e-7,"isMe":true,"addr":"heron.25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","username":"heron","pubKey":"25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","refersToMe":false}
I/System.out: encryptedMessage.toByteString():<ByteString@35144c0 size=403>
E/System:  ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
I/System.out: Queueing new MessageJob
    Queueing new MessageJob end
    Sending text message: {"contentType":"text","content":"11","topic":null,"timestamp":"Fri, 15 Nov 2019 04:14:13 GMT","isPrivate":true,"value":1e-7,"isMe":true,"addr":"heron.25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","username":"heron","pubKey":"25ac590eaca614a0ba4c4387d8514a0b54e948d120c6ff49564e7830c9dec929","refersToMe":false}
I/System.out: encryptedMessage.toByteString():<ByteString@90cf5f9 size=403>
E/System:  ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
     ******** DEPRECATED FUNCTIONALITY ********
     * The implementation of the MessageDigest.SHA-256 algorithm from
     * the BC provider is deprecated in this version of Android.
     * It will be removed in a future version of Android and your
     * application will no longer be able to request it.  Please see
     * https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
     * for more details.
```

**Comment by RealJohnSmith** [comment] 2019-11-15 21:25
Yes, detection of dropped WebSocket takes about a minute or so, I think it is up to 2 minutes. The client reconnects as soon as it is detected. I cannot do much about this as this is in part limitation of WebSocket and in part limitation of network API exposed to java by the system. More specifically, I do not receive an ICMP message informing me about network failure when it occurs.

I am afraid I cant do anything about that. At least not in a portable way. I may change the ping timeout if you really want to, but for the cost that it will be constantly actively sending more messages to check connections, which I suppose you don't really won't since you are developing a mobile app, because of increased data consumption on metered connections and battery usage.

**Comment by yilunzhang** [comment] 2019-11-15 23:29
What's the relationship between the ping timeout and the time to detect ws conn drop?
Also as reference, golang websocket handles this pretty well, but js websocket is not (but it do detect if you try to send a msg using a dropped ws conn)

**Comment by RealJohnSmith** [comment] 2019-11-16 18:22
Well, the smaller the timeout is, the more ping messages you have to send, but you will know sooner that something is wrong.
Afaik, there is no way to detect if the packet failed to send, because of broken pipe (seems like JDK doesn't receive/handle corresponding ICMP message) and therefore I cant detect the connection failure at the time it occurs, but only after my ping fails.

**Comment by yilunzhang** [comment] 2019-11-16 20:38
> Afaik, there is no way to detect if the packet failed to send, because of broken pipe

Since websocket is using TCP, when a packet is sent, it should know if the packet fails to send or not. If the underlying TCP conn has a broken pipe error, it will know because no TCP ACK is ever received. But if the TCP conn only listens for packet but not sending any, then it must wait for long to send a TCP keepalive or ping msg.

What is the current ping interval? And do you mean websocket ping/pong protocol, TCP keepalive, or something else?

**Comment by RealJohnSmith** [comment] 2019-11-18 10:51
> Since websocket is using TCP, when a packet is sent, it should know if the packet fails to send or not. If the underlying TCP conn has a broken pipe error, it will know because no TCP ACK is ever received.

Thats what I thought, but I seems like the java sdk doesn't expose this in their api. I was digging through their sources when I was trying to figure out why I can't get it to reconnect earlier.

Anyway, the ping is set to 1 minute right now. I will probably expose the setting through the sdk

**Comment by iheron** [comment] 2019-11-21 03:20
messageHold.await() blocked send message. If app has something wrong, messageHold.countUp() maybe run twice.

**Comment by yilunzhang** [comment] 2019-11-21 03:34
Let me explain a little bit more: what @iheron found is that sometimes when network lost and reconnect, messageHold somehow becomes >1, and even when ws reconnect, it just go down to 1, so send message will be blocked forever. Not sure how it becomes >1 but if we add some restriction to make sure messageHold <= 1, the problem will be solved...

**Comment by RealJohnSmith** [comment] 2019-11-23 12:20
I have addressed this in my last commit, see if it fixes your issue. It is really hard to test, because of a concurrent and chaotic nature of network & thread scheduling. It should be fixed though

**Comment by yilunzhang** [comment] 2019-11-23 21:25
I believe `messageHold.await()` is what's causing this issue (cannot send but can receive) because it's only blocking msg sending part but not receiving...

**Comment by RealJohnSmith** [comment] 2019-11-24 20:38
Yes, but there was a problem with releasing this lock, which I changed and it seems to work for me now.
messageHold.await() is an important part because you don't want to send messages while you don't have a valid WS connection, you want to queue them instead.
Have you tried the updated version? Does the problem persist?

**Comment by RealJohnSmith** [comment] 2019-11-30 14:19
It seems to me that your problem is solved, closing the issue.

**Closed as completed by RealJohnSmith** 2019-11-30 14:19 UTC
